name: Helm Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          charts_dir: ../
          index_dir: .
          charts_url: https://mrdotb.github.io/helm-charts/
          owner: mrdotb
          repository: helm-charts
          branch: main
          target_dir: plausible-analytics
          dependencies: bitnami,https://charts.bitnami.com/bitnami
          commit_username: mrdotb
          commit_email: mrdotb@protonmail.com
